import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "../styles/home.module.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        href="https://fonts.cdnfonts.com/css/druk-wide-bold"
        rel="stylesheet"
      ></link>
      <link
        href="https://cdn.jsdelivr.net/npm/rubik-font@0.0.3/css/rubik.min.css"
        rel="stylesheet"
      ></link>
      <body className={inter.className}>
        <main className={`h-screen p-4 ${styles.curvedBackgroundGradient}`}>
          {children}
        </main>
      </body>
    </html>
  );
}
